# Package destination directory (within the public directory)
destination:
  javascripts: packaged
  stylesheets: packaged

# Asset source directories (within the public directory)
sources:
  javascripts: js
  stylesheets: css

javascripts:
  js:
    - vendor/underscore
    - vendor/json2
    - vendor/jquery
    - script

stylesheets:
  css:
    - style

